name: text-display-experiments
version: '${project.version}'
main: com.heledron.text_display_experiments.TextDisplayExperimentsPlugin
api-version: '1.20'

commands:
  items:
    description: Open the items menu
    permission: text-display-experiments.items

permissions:
  text-display-experiments.items:
    description: Allows access to the items command
    default: op